### ISSUE TITLE
Rendering any partial fails

### ISSUE THREAD

**Issue by thedumbtechguy** [bullet-train-co/nice_partials#17]
Thank you for this this project. Fits exactly my needs.

I installed the gem and set it up, but now any rendering fails completely.
I have a layout and sub templates.
In the sub templates, putting simple stuff works fine, but once I render a partial, even on a non `nice_partial` partial, I get the error below.
![image](https://user-images.githubusercontent.com/923493/135803418-98992e06-41bf-4ab9-8f90-fcefd8c79025.png)

If I render a `nice_partial` template, I get this.
![image](https://user-images.githubusercontent.com/923493/135803194-322cf961-9890-4580-bbdb-a9969468b2b8.png)

I'm using a graphql setup and this is for emails, so maybe that helps, but I'm not sure what to look out for.

Thank you.

**Comment by thedumbtechguy** [comment]
Hi. Any help on this?

**Comment by andrewculver** [comment]
@thedumbtechguy Are you available for a pairing session? I'd love to get someone on the phone with you to try and debug this issue. Shoot me an email at `andrew` at https://bullettrain.co and let me know your timezone and I'll try to connect you with someone who can help.

**Comment by kaspth** [comment]
NicePartials has changed a lot since this was initially filed, so I'll close this out. @thedumbtechguy thank you for the issue and let us know if you're still seeing issues with the latest v0.1.9 update.
