### ISSUE TITLE
Gem Dependency

### ISSUE THREAD

**Issue by kobaltz** [bullet-train-co/nice_partials#3]
Hello Andrew!

Within the nice_partials.rb, there is a reference to ActionView. However, this is not listed as a gem dependency. Consider adding it so that others will know that this is project has this requirement.

https://github.com/bullet-train-co/nice_partials/blob/96e42bdac6f8207bdc589e13767d756e8cfc214a/lib/nice_partials.rb#L10

Thank you for your contributions!

**Comment by jigarkakadiya** [comment]
@andrewculver  
Added  ActionView reference. Please check fork  https://github.com/jigarkakadiya/nice_partials/tree/narola_dev

**Comment by andrewculver** [comment]
@jigarkakadiya Looked good, thanks for this!
