### ISSUE TITLE
IO and Object Allocation

### ISSUE THREAD

**Issue by tleish** [bullet-train-co/nice_partials#85]
I'm curious if this gem adds any improvement to IO and object allocation similar to how ViewComponent does.

see: [How rendering partials can slow your Rails app to a crawl - TeamHQ](https://teamhq.app/blog/tech/17-how-rendering-partials-can-slow-your-rails-app-to-a-crawl)

**Comment by kaspth** [comment]
Nice Partials just uses the existing rendering structures that Action View has, and we've focused on leveling up partials conceptually, not the rendering performance.

I'd suggest running your own benchmarks too though, partials may be fine for your app. There's also been some work done in newer Rails versions to improve rendering performance, though I don't remember the details.
